---
window:
  decorations: none
  startup_mode: Maximized
  option_as_alt: Both
key_bindings:
  - { key: Key3, mods: Alt, chars: "#" }
font:
  normal:
    family: JetBrainsMono Nerd Font
    style: Regular
  bold:
    family: JetBrainsMono Nerd Font
    style: Bold
  size: 14
draw_bold_text_with_bright_colors: true
colors:
  primary:
    background: '#263238'
    foreground: '#CDD3DE'
  normal:
    black: '#263238'
    red: '#EC5F67'
    green: '#8BD649'
    yellow: '#FFCC00'
    blue: '#89DDFF'
    magenta: '#82AAFF'
    cyan: '#80CBC4'
    white: '#CDD3DE'
  bright:
    black: '#707880'
    red: '#EC5F67'
    green: '#8BD649'
    yellow: '#FFCC00'
    blue: '#89DDFF'
    magenta: '#82AAFF'
    cyan: '#80CBC4'
    white: '#FFFFFF'
