---
colorize: true
style: monokai
formatter: terminal256
cheatpaths:
  - name: community
    path: ~/.config/cheat/cheatsheets/community
    tags: [community]
    readonly: true
  - name: personal
    path: ~/.config/cheat/cheatsheets/personal
    tags: [personal]
    readonly: false
