#
# Executes commands at the start of an interactive session.
#

# add the custom function path
fpath=($DOTFILES/functions $DOTFILES/zsh/functions $fpath)

# autoload all of the custom functions
autoload -U $DOTFILES/functions/*(:t)

# source prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# pull in aliases
source $HOME/.aliases

# configure chruby
source /usr/local/opt/chruby/share/chruby/chruby.sh
source /usr/local/opt/chruby/share/chruby/auto.sh

# pull in zsh-syntax-highlighting
source /usr/local/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
